### ISSUE TITLE
Error ! - Request support

### ISSUE THREAD

**Issue by RobGo88** [clebrw/Parallel-Bitcoin-Brute-Force#2]
C:\Python\Parallel-Bitcoin-Brute-Force-main>parallel_BF_BTC.py 1000 4
> Starting - Bitcoin Brute Force
> CPU count: 6
> Reading Wallets
> 0 Wallets Loaded

>>> Starting Brute Force <<<
Process Process-2:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
Process Process-1:
NameError: name 'wallets' is not defined
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
NameError: name 'wallets' is not defined
Process Process-3:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
NameError: name 'wallets' is not defined
Process Process-4:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
NameError: name 'wallets' is not defined
> 2959.74 Wallets/seg

>>> End Brute Force <<<

C:\Python\Parallel-Bitcoin-Brute-Force-main>

Can you please tell me what I am doing wrong? Thank you very much. Rob

**Comment by RobGo88** [comment]
C:\Python\Parallel-Bitcoin-Brute-Force-main>parallel_BF_BTC.py 1000 4
> Starting - Bitcoin Brute Force
> CPU count: 6
> Reading Wallets
> 6,378 Wallets Loaded

>>> Starting Brute Force <<<
Process Process-1:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
NameError: name 'wallets' is not defined
Process Process-4:
Process Process-2:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Process Process-3:
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
NameError: name 'wallets' is not defined
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
Traceback (most recent call last):
NameError: name 'wallets' is not defined
  File "C:\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Parallel-Bitcoin-Brute-Force-main\parallel_BF_BTC.py", line 9, in BF_random
    if pk.address in wallets:
NameError: name 'wallets' is not defined
> 2965.82 Wallets/seg

>>> End Brute Force <<<

C:\Python\Parallel-Bitcoin-Brute-Force-main>

**Comment by clebrw** [comment]
Hi Rob. Did you install the 'bit' library? what operating system are you using?

**Comment by RobGo88** [comment]
Hello and thank you for the quick reply.
Yes the "bit" library is installed.
I use WIN 64 and start the program via cmd.

**Comment by clebrw** [comment]
Hi. I made a modification and believe it is working. Could it be for me? thanks.

**Comment by RobGo88** [comment]
Hello.
Thanks for your support, just tested it. (see below)
1. at startup the program does not take 4 cores but 6.
2. after start it takes about 3 seconds, then the program is finished.
3. looks like the program does nothing.

THX Rob

C:\Python\Parallel-Bitcoin-Brute-Force-main>parallel_BF_BTC.py 1000 4
> Starting - Bitcoin Brute Force
> CPU count: 6
> Reading Wallets
> 6,378 Wallets Loaded

>>> Starting Brute Force <<<
> 2961.1 Wallets/seg

>>> End Brute Force <<<

**Comment by clebrw** [comment]
Great, thanks for the tests.

Your computer is computing 1000 wallets and this is very little for a wallet file with 6000 wallets. In my test I used a txt file with 23 million wallets, approximately 800MB of txt.

You can increase the number of tests and also the number of processors. Try "python3 parallel_BF_BTC.py 10000000 6" so you will test 10 Million addresses using 6 processes in python, you can probably make a coffee while you wait :)

**Comment by RobGo88** [comment]
Hello.
Now it works, thanks for the help and the hint.
Greetings Rob
